name: API Tests - REST Assured

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:

  api-tests:

    name: API Automation Tests

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5


      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven


      - name: Check Java version
        run: java -version


      - name: Check Maven version
        run: mvn -version


      - name: Validate Maven project
        run: mvn validate
        working-directory: ./RestAssured/projeto01/restassured


      - name: Compile tests
        run: mvn test-compile
        working-directory: ./RestAssured/projeto01/restassured


      - name: Run API tests
        run: mvn clean test
        working-directory: ./RestAssured/projeto01/restassured


      - name: Tests completed successfully
        if: success()
        run: echo "API automation tests completed successfully."


      - name: Tests failed
        if: failure()
        run: echo "API automation tests failed."
